/* Limited, source-linked screening. This is not a comprehensive interaction database. */
(function(root){
  const evidence={statin:'https://sps.nhs.uk/articles/managing-interactions-between-macrolides-and-statins/',nsaid:'https://www.nhs.uk/medicines/nsaids/',paracetamol:'https://www.nhs.uk/medicines/paracetamol-for-adults/'};
  const guidance = [
    {match:/metformin/,name:'Metformin',food:'Take with food. Follow the instructions for your exact formulation.',effects:'Common effects include nausea, diarrhoea, abdominal discomfort and reduced appetite. Vitamin B12 deficiency can occur.',caution:'Ask for advice if vomiting, diarrhoea or fever could cause dehydration, or if you have kidney or liver problems.',url:'https://www.nhs.uk/medicines/metformin/'},
    {match:/ibuprofen|nurofen/,name:'Ibuprofen',food:'For ordinary oral tablets or capsules, take with water, ideally with or after food. This does not apply to gel or spray.',effects:'Can cause indigestion or stomach pain; more serious effects include stomach bleeding and kidney problems.',caution:'Check suitability with asthma, ulcers, heart or kidney disease, pregnancy, blood thinners or other NSAIDs. Food does not remove these risks.',url:'https://www.nhs.uk/medicines/ibuprofen-for-adults/'},
    {match:/paracetamol|acetaminophen|paralief|panadol/,name:'Paracetamol',food:'Oral tablets or capsules can be taken with or without food.',effects:'Side effects are uncommon when used correctly. Too much can cause serious harm even if you initially feel well.',caution:'Do not combine products containing paracetamol. Check suitability with liver or kidney disease; seek urgent medical advice after taking too much.',url:'https://www.nhs.uk/medicines/paracetamol-for-adults/'},
    {match:/co.?amoxiclav|amoclav|augmentin|amoxicillin.*clavulan|clavulan.*amoxicillin/,name:'Co-amoxiclav',food:'Take with a meal to help reduce nausea and vomiting.',effects:'Diarrhoea, nausea, vomiting or thrush can occur.',caution:'Tell your prescriber about penicillin allergy or previous liver problems with antibiotics. Follow the prescribed course and ask about severe or persistent diarrhoea.',url:'https://www.nhs.uk/medicines/co-amoxiclav/'},
    {match:/clarithromycin/,name:'Clarithromycin',food:'Standard tablets can be taken with or without food. For modified-release products, confirm the specific leaflet instructions.',effects:'Check the patient leaflet for possible side effects and when to seek help.',caution:'Check interactions, especially statins. Complete the course as prescribed and do not double a dose to make up for a missed one.',url:'https://www.nhs.uk/medicines/clarithromycin/how-and-when-to-take-clarithromycin/'},
    {match:/atorvastatin/,name:'Atorvastatin',food:'Can be taken with or without food, at a consistent time each day.',effects:'Check the leaflet for side effects. Unexplained muscle symptoms need medical advice.',caution:'Some antibiotics interact with atorvastatin. Excess grapefruit juice and heavy alcohol use can increase risks; tell your clinician about liver problems.',url:'https://www.nhs.uk/medicines/atorvastatin/'}
  ];
  function info(medicine){const text=(medicine.name+' '+(medicine.ingredient||'')).toLowerCase();return guidance.filter(g=>g.match.test(text));}
  function card(medicine){
    const esc=window.MediCare.escape,items=info(medicine);
    return '<div class="medicine-instructions">'+(items.length?items.map(g=>'<h4>'+esc(g.name)+' · Practical guidance</h4><p><strong>Food: </strong>'+esc(g.food)+'</p><p><strong>Side effects: </strong>'+esc(g.effects)+'</p><p><strong>Check first: </strong>'+esc(g.caution)+'</p><a class="source-link" href="'+esc(g.url)+'" target="_blank" rel="noopener noreferrer">Source: NHS · '+esc(g.name)+'</a>').join(''):'<p>Food instructions, side effects and interactions have not been checked for this medicine. Follow your product leaflet and ask a pharmacist.</p>')+'</div>';
  }
  function screen(medicines,conditions){
    const text=medicines.map(m=>(m.name+' '+(m.ingredient||'')).toLowerCase());
    const profile=conditions.map(c=>c.label||c.id).join(' ').toLowerCase();
    const has=re=>text.some(t=>re.test(t));const flags=[];
    if(has(/clarithromycin|erythromycin/)&&has(/atorvastatin|simvastatin/))flags.push({title:'Antibiotic and statin interaction',message:'This macrolide antibiotic can increase the risk of muscle injury with these statins. A prescriber must review the combination before it is taken. Do not choose a replacement or change a prescribed dose yourself.',url:evidence.statin});
    if(text.filter(t=>/paracetamol|acetaminophen|co-codamol|co-dydramol|paralief|panadol/.test(t)).length>1)flags.push({title:'Possible duplicate paracetamol',message:'More than one product may contain paracetamol (acetaminophen). Combining them can cause overdose. Check all active ingredients with a pharmacist before taking them together.',url:evidence.paracetamol});
    if(text.filter(t=>/ibuprofen|naproxen|diclofenac|aspirin|nurofen/.test(t)).length>1)flags.push({title:'More than one anti-inflammatory medicine',message:'Taking multiple NSAIDs can increase side effects, including stomach bleeding. Ask your prescriber or pharmacist to review these products.',url:evidence.nsaid});
    if(has(/ibuprofen|naproxen|diclofenac|nurofen/) && (/asthma|kidney|renal|ulcer|heart|hypertension|high bp|high blood|liver/.test(profile)||has(/warfarin|apixaban|rivaroxaban|dabigatran|clopidogrel/)))flags.push({title:'Anti-inflammatory medicine needs review',message:'An NSAID may not be suitable with your recorded conditions or a blood-thinning medicine. Consult your doctor or pharmacist before use.',url:evidence.nsaid});
    if(has(/metformin/)&&has(/ibuprofen|diclofenac|naproxen/))flags.push({title:'Metformin and anti-inflammatory review',message:'Some anti-inflammatory medicines may not mix well with metformin. Ask your pharmacist or doctor to review the combination, particularly if dehydrated or with kidney problems.',url:'https://www.nhs.uk/medicines/metformin/'});
    return flags;
  }
  if(typeof module!=='undefined')module.exports={screen,info};else root.MedicineSafety={screen,info,card};
})(typeof window!=='undefined'?window:globalThis);
